name: stillshape

services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/html
      - /html/node_modules
    environment:
      NODE_ENV: development
      APP_PORT: 4000
